#!/usr/bin/python
from distutils.core import setup;

setup(name = "PPLT",
      version="0.3.1",
      description="PPLT a free industrial communication framework",
      author="Hannes Matuschek",
      author_email="hmatuschek@gmx.net",
      url='http://pplt.berlios.de',
      packages=['pyDCPU',
                'pyDCPU.UserDB',
                'pyDCPU.Modules',
                'PPLT',
				'PPLT.Center'],
      scripts =["Scripts/PPLTModInstall.py","Scripts/PPLTC.py","PPLT_PostInstall.py"],
      data_files = [('PPLT',["UserDB.xml","PPLT.conf"]),
                    ('PPLT/icons',['icons/PPLTSessionFile.ico',
                                   'icons/PPLT.ico',
                                   'icons/proxy.xpm',
                                   'icons/user.xpm',
                                   'icons/group.xpm',
                                   'icons/superuser.xpm',
                                   'icons/class.xpm',
                                   'icons/device.xpm',
                                   'icons/folder.xpm',
                                   'icons/folder2.xpm',
                                   'icons/pack_add.xpm',
                                   'icons/server.xpm',
                                   'icons/slot-range.xpm',
                                   'icons/slot.xpm',
                                   'icons/symbol.xpm',
                                   'icons/info.xpm',
                                   'icons/new.xpm',
                                   'icons/load.xpm',
                                   'icons/saveas.xpm',
                                   'icons/save.xpm']),
                    ('PPLT/de/LC_MESSAGES',['I18N/de/PPLT.mo'])],
      long_description="PPLT is an industrial communication framework.",
      classifiers = [
        'Intended Audience :: Developers',
        'License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)',
        'License :: OSI Approved :: GNU General Public License (GPL)',
        'Natural Language :: English',
        'Natural Language :: German',
        'Operating System :: POSIX',
        'Operating System :: Microsoft :: Windows',
        'Programming Language :: Python',
        'Topic :: Communications',
        'Topic :: Software Development :: Libraries',
    ]);
