################################################## 
# ./OPC_wsdl_services_types.py 
# generated by ZSI.wsdl2python 
# 
# 
##################################################


import ZSI
from ZSI.TCcompound import Struct

############################## 
# targetNamespace 
#
# http://opcfoundation.org/webservices/XMLDA/1.0/ 
##############################


# imported as: ns1
class opcfoundation_org_webservices_XMLDA_1_0:
    targetNamespace = 'http://opcfoundation.org/webservices/XMLDA/1.0/'

# define class alias for subsequent ns classes
ns1 = opcfoundation_org_webservices_XMLDA_1_0



